# Generated by Django 4.2.2 on 2023-06-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default='test body'),
            preserve_default=False,
        ),
    ]
