# Generated by Django 4.2.2 on 2023-06-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_album_musician_delete_person_album_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='shirt_sizes',
            field=models.CharField(choices=[('L', 'large'), ('M', 'medium'), ('S', 'small')], default='medium', max_length=1),
        ),
    ]
