# Generated by Django 4.2.2 on 2023-06-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_manufacturer_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default='Chevy', max_length=100),
        ),
    ]
