# Generated by Django 4.2.2 on 2023-06-29 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='shelves',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cbv.shelf'),
            preserve_default=False,
        ),
    ]
