# Generated by Django 4.2.2 on 2023-06-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0002_floor_shelves'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
